### PR TITLE
Parse a line based on the number of bytes or charcaters

### PR DESCRIPTION
**Pull request by RandomString123**
@bkamins I am going to merge this code in soon but using pull requests so you can see and merge it to yours if needed.  These modifications do the following: 

* Disable column based parsing until I can figure out how to do it reliably using characters or bytes
* Adds functionality to accept a new Boolean `unitbytes` that will parse the file using bytes as the unit, or alternatively characters as the unit
* Modifies `readsplitline!` so it will parse a line based on bytes or characters
* Added functions `parsebyte_line` `parsechar_line` to support `readsplitline!`
* Added unit tests for new functions
* Added unit tests to ensure parsing of our test case `"α1x\na2y\n∀∅z"` works

My code assumes that the units used in column widths are bytes or characters as defined by the Boolean `unitbytes`.  So [1:1,2:2,3:3] or [1,1,1] will parse the above utf8 string.

### CODE REVIEW

**Comment by bkamins** [comment]
Nice, actually I have a very similar implementation with the difference how `readsplitline!` is implemented, as in your code indexing with character index will be slow (but maybe we can ignore this for now and focus on functionality). Here is my code for your consideration (I am copying a relevant part):

```
    chr = 0
    ind = 0
    # Break it up into chunks
    for range in columnwidths
        if byteindex
            str = SubString(line, range)
        else
            # this code will be simpler when only Julia 0.7 or higher is supported
            while chr < first(range)
                ind = nextind(line, ind)
                chr += 1
            end
            ind_start = ind
            while chr < last(range)
                ind = nextind(line, ind)
                chr += 1
            end
            ind_stop = ind
            str = SubString(line, ind_start:ind_stop)
        end
        trim && (str = strip(str))
        push!(vals, str)
    end
    return vals
```
This code assumes that `columnwidths` have increasing ranges, but this is an invariant that we know is met. The benefit is that we traverse `line` only once. With `SubString` we have to traverse it every time we create a `SubString`.

I did not push it because I was thinking what to do with checking of line length `row_countlines` as it was very byte-oriented, but I can see you have disabled it 😄.

EDIT: some corrections in the code to make it type stable.

**Comment by bkamins** [comment]
One comment - I have named the condition `byteindex` which shoud be `unitbytes || isascii(line)` in your code.

**Comment by RandomString123** [comment]
I like yours better also.  I was trying to make the code from your repo work but got hung up on the functions not working .6 so I just went with what was fast to implement.  i will try putting that code into this PR right now and test.

**Comment by bkamins** [comment]
When we leave support for 0.6 someday we can use `nextind(s, i, n)` which moves ahead by `n` characters, but for now `while` loop is needed moving by one character each time.

**Comment by RandomString123** [comment]
I saw that.  At first I tried to just cut and paste your code into mine but it failed for that missing signature.  

I integrated your code into this PR.  I made one change to it.  You were not pulling the range out of the line at the end of your column loop so it ended up just pushing a bunch of blank strings into the return value.  I had to make a slight adjustment to the last iteration of the loop because nextind returns an out of bounds index.  (Something else I saw you fixed in the same PR that modified nextind)

**Comment by RandomString123** [comment]
Merging this into the main branch

**Pull request merged**
